/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 깔깔룩위원회 API OpenAPI Document
 * OpenAPI spec version: 0.0.1
 */
import type { Picture } from "./picture";

export interface EvaluationItemResponseDto {
  id: number;
  title: string;
  nickname: string;
  hashtagList: string[];
  totalScore: number;
  picture: Picture;
}
