/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 깔깔룩위원회 API OpenAPI Document
 * OpenAPI spec version: 0.0.1
 */

export interface KakakoLoginRequestDto {
  /** Kakao Oauth Code */
  code: string;
  /** Kakao Oauth Code redirected source URI */
  redirectUri: string;
}
